version: "2"
linters:
  enable:
    - errcheck
    - gochecknoinits
    - govet
    - ineffassign
    - lll
    - noctx
    - staticcheck
    - unused
  settings:
    lll:
      line-length: 120
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoinits
        path: cmd/mcp_start.go
      - linters:
          - gochecknoinits
        path: mcp/server.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
