version: 2

project_name: mongo-migration-tool

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: mongo-tool
    binary: mongo-tool
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - readme.md
      - LICENSE
      - mcp.md
      - .env.example
      - examples/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^refactor:'
      - '^style:'
      - '^build:'
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: 'MCP Integration'
      regexp: '^.*?mcp(\(.+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

brews:
  - name: mongo-tool
    repository:
      owner: drewjocham
      name: homebrew-mongo-migration
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/drewjocham/mongo-migration-tool
    description: "MongoDB migration tool with MCP support"
    license: MIT
    dependencies:
      - name: mongodb/brew/mongodb-community
        type: optional
    install: |
      bin.install "mongo-tool"
      pkgshare.install ".env.example"
      pkgshare.install "examples"
      pkgshare.install "mcp.md"
    test: |
      system "#{bin}/mongo-tool --version"

dockers:
  - image_templates:
      - "ghcr.io/drewjocham/mongo-migration-tool:{{ .Version }}-amd64"
      - "ghcr.io/drewjocham/mongo-migration-tool:latest-amd64"
    dockerfile: docker/Dockerfile.release
    use: buildx
    ids:
      - mongo-tool
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/drewjocham/mongo-migration-tool"
  - image_templates:
      - "ghcr.io/drewjocham/mongo-migration-tool:{{ .Version }}-arm64"
      - "ghcr.io/drewjocham/mongo-migration-tool:latest-arm64"
    dockerfile: docker/Dockerfile.release
    use: buildx
    ids:
      - mongo-tool
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/drewjocham/mongo-migration-tool"

docker_manifests:
  - name_template: "ghcr.io/drewjocham/mongo-migration-tool:{{ .Version }}"
    image_templates:
      - "ghcr.io/drewjocham/mongo-migration-tool:{{ .Version }}-amd64"
      - "ghcr.io/drewjocham/mongo-migration-tool:{{ .Version }}-arm64"
  - name_template: "ghcr.io/drewjocham/mongo-migration-tool:latest"
    image_templates:
      - "ghcr.io/drewjocham/mongo-migration-tool:latest-amd64"
      - "ghcr.io/drewjocham/mongo-migration-tool:latest-arm64"

release:
  github:
    owner: drewjocham
    name: mongo-migration-tool
  replace_existing_artifacts: true
  header: |
    Generated by GoReleaser for {{.ProjectName}}
    
    ### Installation

    #### Homebrew (macOS/Linux)
    ```bash
    brew tap drewjocham/tap
    brew install mongo-migration
    ```

    #### Go Install
    ```bash
    go install [github.com/drewjocham/mongo-migration-tool@v](https://github.com/drewjocham/mongo-migration-tool@v){{.Version}}
    ```

    #### Docker
    ```bash
    docker run --rm -v $(pwd):/app ghcr.io/drewjocham/mongo-migration-tool:{{.Version}} --help
    ```
  footer: |
    ## Thank You!
    For more detailed information, please see the [documentation](https://pkg.go.dev/github.com/drewjocham/mongo-migration-tool).

nfpms:
  - id: packages
    package_name: mongo-migration
    homepage: https://github.com/drewjocham/mongo-migration-tool
    description: MongoDB migration tool with MCP support
    maintainer: Drew Jocham <mongo@jocham.io>
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

announce:
  skip: true
