# syntax=docker/dockerfile:1.7
FROM alpine:3.23

RUN apk --no-cache add ca-certificates tzdata \
    && adduser -D -s /bin/sh migration

WORKDIR /app

COPY mongo /usr/local/bin/mongo

USER migration

ENTRYPOINT ["/usr/local/bin/mongo"]
CMD ["--help"]
