// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {main} from '../models';

export function AskAI(arg1:string):Promise<string>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CreateMigration(arg1:string):Promise<string>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect():Promise<string>;

export function Down(arg1:string,arg2:boolean):Promise<string>;

export function GetAIKey():Promise<string>;

export function GetDBHealth():Promise<desktop.HealthReport>;

export function GetMCPActivity(arg1:number):Promise<Array<Record<string, any>>>;

export function GetMCPServerStatus():Promise<Record<string, any>>;

export function GetMigrationsPath():Promise<string>;

export function GetOplog(arg1:number):Promise<Array<any>>;

export function GetOpslog(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<Array<desktop.MigrationRecord>>;

export function GetSchemaDiff():Promise<Array<desktop.Diff>>;

export function GetSchemaIndexes():Promise<Array<desktop.IndexSpec>>;

export function GetStatus():Promise<Array<desktop.MigrationStatus>>;

export function LoadConnections():Promise<Array<main.SavedConnection>>;

export function ParseConnectionString(arg1:string):Promise<Record<string, string>>;

export function SaveConnection(arg1:main.SavedConnection):Promise<void>;

export function SetAIKey(arg1:string):Promise<void>;

export function SetMigrationsPath(arg1:string):Promise<void>;

export function StartMCPServer(arg1:string,arg2:string):Promise<string>;

export function StopMCPServer():Promise<string>;

export function Up(arg1:string,arg2:boolean):Promise<string>;
