// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function CreateMigration(arg1) {
  return window['go']['main']['App']['CreateMigration'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function Down(arg1, arg2) {
  return window['go']['main']['App']['Down'](arg1, arg2);
}

export function GetAIKey() {
  return window['go']['main']['App']['GetAIKey']();
}

export function GetDBHealth() {
  return window['go']['main']['App']['GetDBHealth']();
}

export function GetMCPActivity(arg1) {
  return window['go']['main']['App']['GetMCPActivity'](arg1);
}

export function GetMCPServerStatus() {
  return window['go']['main']['App']['GetMCPServerStatus']();
}

export function GetMigrationsPath() {
  return window['go']['main']['App']['GetMigrationsPath']();
}

export function GetOplog(arg1) {
  return window['go']['main']['App']['GetOplog'](arg1);
}

export function GetOpslog(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetOpslog'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetSchemaDiff() {
  return window['go']['main']['App']['GetSchemaDiff']();
}

export function GetSchemaIndexes() {
  return window['go']['main']['App']['GetSchemaIndexes']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function LoadConnections() {
  return window['go']['main']['App']['LoadConnections']();
}

export function ParseConnectionString(arg1) {
  return window['go']['main']['App']['ParseConnectionString'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SetAIKey(arg1) {
  return window['go']['main']['App']['SetAIKey'](arg1);
}

export function SetMigrationsPath(arg1) {
  return window['go']['main']['App']['SetMigrationsPath'](arg1);
}

export function StartMCPServer(arg1, arg2) {
  return window['go']['main']['App']['StartMCPServer'](arg1, arg2);
}

export function StopMCPServer() {
  return window['go']['main']['App']['StopMCPServer']();
}

export function Up(arg1, arg2) {
  return window['go']['main']['App']['Up'](arg1, arg2);
}
